export const adminUrl = {
  dashboard: "admin/dashboard",
  login: "admin/login",
  changePassword: "admin/changePassword",
  sendOtp: "admin/sendotp",
  adminFrogotPassword: "admin/forgot",
  logout: "admin/logout",
  school: "admin/school",
  userPermission: "admin/permissions",
  notification: "admin/notification",
  // state
  state: "common/state",
  district: "common/district",

  // plan

  ticket: "admin/ticket",
  role: "admin/role",
  user: "admin/user",
  coupon: "admin/coupon",
  smsTamplate: "admin/sms/template",
  //gymmmmm
  plan: "admin/plan",
  gym: "admin/gym",
};
export const userUrl = {
  dashboard: "/dashboard",
  login: "/login",
  plan: "/gymPlan",
  offer: "/offer",
  client: "/gymClient",
  renew: "/renew",
  bulkImport: "/gymClient/bulk-import",
  logout: "/logout",
  changePassword: "/change-password",
  profile: "/gym-profile",
  subscriptionPlans: "/subscription/plans",
  subscriptionHistory: "/subscription/history",
  currentSubscription: "/subscription/current",
  subscriptionCreateOrder: "/subscription/create-order",
  subscriptionVerifyPayment: "/subscription/verify-payment",
  subscriptionActivate: "/subscription/activate",
  //

  sendOtp: "institute/sendotp",
  userFrogotPassword: "institute/forgot",
  notification: "institute/notification",
  updateProfile: "institute/update",
  master: "institute/master",
  student: "institute/student/",
  searchStudent: "institute/student/search",
  upgradePlan: "institute/plan/payment",
  planHistory: "institute/plan/allPlan",
  paymentStatus: "institute/plan/status",
  studentLimit: "institute/student/limit",
  holiday: "institute/holiday",
  notifyParent: "institute/attendance/sendPresentMessage",
  attendance: "institute/attendance",
  log: "institute/attendance/getStudentDayPunch",
  attendanceReport: "institute/attendance/report/",
  attendanceReportTable: "institute/attendance/report/table",
  sms: "institute/sms/setting",
  smsTamplate: "institute/sms/template",
  ticket: "institute/ticket",
  device: "institute/bioDevice",
  shift: "institute/shift",
  studentPromotion: "institute/student/promotion",
};
